### ISSUE TITLE
Encountered error in CoreList documentation

### ISSUE THREAD

**Issue by aitijhyasarkar** [wrappid/guide-module#91]
## Describe the bug
While working on issue #15, I noticed that clicking on CoreList throws an error. There may be an error in CoreList.docs.js, which I did not notice at first glance.

## To Reproduce
1. Start the frontend app.
2. Navigate to `127.0.0.1:3000/guide/components`.
3. Attempt to access the CoreList documentation.
4. Observe the error, causing the frontend app to break until refreshed.

## Expected behavior
Users must have a seamless and error-free experience while navigating the guide of our framework.

## Screenshots
![e620ad97-bd3a-4b12-b45c-21ed2d353e92](https://github.com/wrappid/guide-module/assets/91305796/27746ebe-d73f-43ba-b5f2-9ac80e1872fd)

## Environment Details
- **Desktop:**
  - **OS:** Windows
  - **Browser:** Chrome
- **Wrappid:**
  - **Version:** 0.0.107

**Comment by aitijhyasarkar** [comment]
Also encountered in CoreListItemIcon

**Comment by aitijhyasarkar** [comment]
Encountered error in CoreTimer-

ERROR
Cannot read properties of undefined (reading 'toString')
TypeError: Cannot read properties of undefined (reading 'toString')
    at CoreTimer (http://127.0.0.1:3000/static/js/bundle.js:136437:90)
    at renderWithHooks (http://127.0.0.1:3000/static/js/bundle.js:266754:22)
    at mountIndeterminateComponent (http://127.0.0.1:3000/static/js/bundle.js:270038:17)
    at beginWork (http://127.0.0.1:3000/static/js/bundle.js:271334:20)
    at HTMLUnknownElement.callCallback (http://127.0.0.1:3000/static/js/bundle.js:256350:18)
    at Object.invokeGuardedCallbackDev (http://127.0.0.1:3000/static/js/bundle.js:256394:20)
    at invokeGuardedCallback (http://127.0.0.1:3000/static/js/bundle.js:256451:35)
    at beginWork$1 (http://127.0.0.1:3000/static/js/bundle.js:276315:11)
    at performUnitOfWork (http://127.0.0.1:3000/static/js/bundle.js:275563:16)
    at workLoopSync (http://127.0.0.1:3000/static/js/bundle.js:275486:9)

**Comment by aitijhyasarkar** [comment]
Encountered error in CoreAutoComplete-

ERROR
renderInput is not a function
TypeError: renderInput is not a function
    at Autocomplete (http://127.0.0.1:3000/static/js/bundle.js:54587:17)
    at renderWithHooks (http://127.0.0.1:3000/static/js/bundle.js:266754:22)
    at updateForwardRef (http://127.0.0.1:3000/static/js/bundle.js:269323:24)
    at beginWork (http://127.0.0.1:3000/static/js/bundle.js:271370:20)
    at HTMLUnknownElement.callCallback (http://127.0.0.1:3000/static/js/bundle.js:256350:18)
    at Object.invokeGuardedCallbackDev (http://127.0.0.1:3000/static/js/bundle.js:256394:20)
    at invokeGuardedCallback (http://127.0.0.1:3000/static/js/bundle.js:256451:35)
    at beginWork$1 (http://127.0.0.1:3000/static/js/bundle.js:276315:11)
    at performUnitOfWork (http://127.0.0.1:3000/static/js/bundle.js:275563:16)
    at workLoopSync (http://127.0.0.1:3000/static/js/bundle.js:275486:9)

**Comment by aitijhyasarkar** [comment]
Encountered error in CoreCheckBox-

ERROR
Cannot read properties of undefined (reading 'fontSize')
TypeError: Cannot read properties of undefined (reading 'fontSize')
    at Checkbox (http://127.0.0.1:3000/static/js/bundle.js:60774:66)
    at renderWithHooks (http://127.0.0.1:3000/static/js/bundle.js:266754:22)
    at updateForwardRef (http://127.0.0.1:3000/static/js/bundle.js:269323:24)
    at beginWork (http://127.0.0.1:3000/static/js/bundle.js:271370:20)
    at HTMLUnknownElement.callCallback (http://127.0.0.1:3000/static/js/bundle.js:256350:18)
    at Object.invokeGuardedCallbackDev (http://127.0.0.1:3000/static/js/bundle.js:256394:20)
    at invokeGuardedCallback (http://127.0.0.1:3000/static/js/bundle.js:256451:35)
    at beginWork$1 (http://127.0.0.1:3000/static/js/bundle.js:276315:11)
    at performUnitOfWork (http://127.0.0.1:3000/static/js/bundle.js:275563:16)
    at workLoopSync (http://127.0.0.1:3000/static/js/bundle.js:275486:9)

**Comment by aitijhyasarkar** [comment]
Encountered error in CoreToolbar-

ERROR
Cannot read properties of undefined (reading 'accessToken')
TypeError: Cannot read properties of undefined (reading 'accessToken')
    at CoreAppBar (http://127.0.0.1:3000/static/js/bundle.js:150546:69)
    at renderWithHooks (http://127.0.0.1:3000/static/js/bundle.js:266754:22)
    at mountIndeterminateComponent (http://127.0.0.1:3000/static/js/bundle.js:270038:17)
    at beginWork (http://127.0.0.1:3000/static/js/bundle.js:271334:20)
    at beginWork$1 (http://127.0.0.1:3000/static/js/bundle.js:276293:18)
    at performUnitOfWork (http://127.0.0.1:3000/static/js/bundle.js:275563:16)
    at workLoopSync (http://127.0.0.1:3000/static/js/bundle.js:275486:9)
    at renderRootSync (http://127.0.0.1:3000/static/js/bundle.js:275459:11)
    at recoverFromConcurrentError (http://127.0.0.1:3000/static/js/bundle.js:274951:24)
    at performSyncWorkOnRoot (http://127.0.0.1:3000/static/js/bundle.js:275160:24)

**Comment by irkfaisal** [comment]
no work done from my side on this issue
